version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - cd file-processor
      - npm ci
  build:
    commands:
      - echo "Building Lambda function..."
      - cd file-processor
      - npm run build  # TODO: Add build script to package.json
      - echo "Creating deployment package..."
      - mkdir -p ../dist
      - cp -r dist/* ../dist/  # TODO: Adjust based on actual build output
      - cp package*.json ../dist/
      - cd ../dist
      - npm ci --production  # Install only production dependencies
  post_build:
    commands:
      - echo "Preparing artifact..."
      - cd ../dist
      - zip -r ../file-processor.zip ./*
      # TODO: Add Lambda deployment commands here
      # aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://../file-processor.zip
      # TODO: Add DynamoDB stream event source mapping if needed

artifacts:
  files:
    - file-processor.zip
  discard-paths: yes
