version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Listing files:"
      - ls -la
      - echo "Checking for functions directory:"
      - ls -la functions/ || echo "functions directory not found"
      - echo "Installing dependencies..."
      - |
        if [ -d "functions/file-processor" ]; then
          cd functions/file-processor
          npm ci
          cd ../..
        else
          echo "ERROR: functions/file-processor directory not found!"
          exit 1
        fi
  build:
    commands:
      - echo "Building Lambda function..."
      - |
        if [ -d "functions/file-processor" ]; then
          cd functions/file-processor
        else
          echo "ERROR: functions/file-processor directory not found!"
          exit 1
        fi
      - npm run build
      - echo "Pruning dev dependencies..."
      - npm prune --production
      - echo "Creating zip with proper structure..."
      - |
        if [ -d "dist" ]; then
          cd dist
          zip -r ../../../file-processor-function.zip *
          cd ..
        else
          echo "ERROR: dist directory not found after build!"
          exit 1
        fi
      - |
        if [ -d "node_modules" ]; then
          zip -r ../../file-processor-function.zip node_modules
        else
          echo "WARNING: node_modules directory not found"
        fi
      - cd ../..
      - echo "Deploying Lambda function via pipeline..."
      - |
        if [ -z "$FUNCTION_NAME" ]; then
          FUNCTION_NAME="MnemosyneFileProcessor"
        fi
        aws lambda update-function-code --function-name "$FUNCTION_NAME" --zip-file fileb://file-processor-function.zip
      - echo "Lambda deployment complete"
