version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - cd file-processor
      - npm ci
  build:
    commands:
      - echo "Building Lambda function..."
      - cd file-processor
      - npm run build
      - echo "Pruning dev dependencies..."
      - npm prune --production
      - echo "Creating zip with proper structure..."
      - cd dist
      - zip -r ../../file-processor-function.zip *
      - cd ..
      - zip -r ../file-processor-function.zip node_modules
      - cd ..
      - echo "Deploying Lambda function via pipeline..."
      - |
        if [ -z "$FUNCTION_NAME" ]; then
          FUNCTION_NAME="MnemosyneFileProcessor"
        fi
        aws lambda update-function-code --function-name "$FUNCTION_NAME" --zip-file fileb://file-processor-function.zip
      - echo "Lambda deployment complete"
