version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd infrastructure && 
      - npm install 
      - npm run build
  build:
    commands:
      - npx cdk deploy --all --require-approval never  --region eu-west-1