version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - n 20
      - npm install -g aws-cdk
  build:
    commands:
      - cd infrastructure
      - npm ci
      - npm run build
      - npx cdk synth --quiet
      - npx cdk deploy --all --require-approval never --outputs-file outputs.json
cache:
  key: infra-$(codebuild-hash-files infrastructure/package-lock.json infrastructure/package.json)
  paths:
    - "infrastructure/node_modules/**/*"
artifacts:
  files:
    - "infrastructure/cdk.out/**/*"
  name: InfrastructureArtifact
