version: 0.2

phases:
  install:
    commands:
      - npm install -g aws-cdk
  build:
    commands:
      - cd infrastructure
      - npm ci
      - npm run build
      - npx cdk synth
      - npx cdk deploy --all --require-approval never --outputs-file outputs.json
