version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - n 20
      - node --version
      - npm --version
      - npm install

  pre_build:
    commands:
      - echo "=== Checking for lambda changes ==="
      - BUILD_TYPE=lambdas node infrastructure/scripts/check-changes.js
      - |
        ENV_FILE="${CODEBUILD_SRC_DIR:-.}/build-changes.env"
        if [ -f "${ENV_FILE}" ]; then
          set -a  # automatically export all variables
          source "${ENV_FILE}" || . "${ENV_FILE}"
          set +a
          echo "Loaded HAS_CHANGES=${HAS_CHANGES} from ${ENV_FILE}"
        else
          echo "WARNING: ${ENV_FILE} not found, defaulting to HAS_CHANGES=true"
          export HAS_CHANGES=true
        fi
      - echo "HAS_CHANGES=${HAS_CHANGES}"
      - |
        if [ "${HAS_CHANGES}" = "false" ]; then
          echo "No changes detected - skipping lambda builds"
          exit 0
        else
          echo "Changes detected - proceeding with build"
          node infrastructure/scripts/setup-lambdas-env.js
          export LAYER_ARN="${LAYER_ARN}"
        fi

  build:
    commands:
      - |
        ENV_FILE="${CODEBUILD_SRC_DIR:-.}/build-changes.env"
        if [ -f "${ENV_FILE}" ]; then
          set -a
          source "${ENV_FILE}" || . "${ENV_FILE}"
          set +a
        fi
      - |
        if [ "${HAS_CHANGES:-true}" = "false" ]; then
          echo "Skipping build phase - no changes"
          exit 0
        fi
      - npm run build:lambdas
      - npm run deploy:lambdas

cache:
  key: lambdas-$(codebuild-hash-files package-lock.json package.json functions/message-listener/package.json functions/file-processor/package.json functions/oauth-callback/package.json)
  paths:
    - 'node_modules/**/*'
    - 'functions/*/node_modules/**/*'

artifacts:
  files:
    - 'message-listener-function.zip'
    - 'file-processor-function.zip'
    - 'oauth-callback-function.zip'
  name: LambdaArtifacts