version: 0.2

phases:
  install:
    commands:
      # No npm install needed - we use pre-built artifacts!
      - aws --version
      - echo "Using pre-built artifacts from Build stage"

  build:
    commands:
      - echo "=== DEPLOY PHASE: Deploying with pre-built artifacts ==="
      - |
        APP_PREFIX="${APP_PREFIX:-Mnemosyne}"
        LAYER_NAME="${APP_PREFIX}SlackSharedLayer"
        echo "App Prefix: ${APP_PREFIX}"
        echo "Layer Name: ${LAYER_NAME}"
      # Cleanup old layer versions (keep last 5)
      - |
        echo "Cleaning up old layer versions..."
        LIST_OUTPUT=$(aws lambda list-layer-versions --layer-name "$LAYER_NAME" --query 'LayerVersions[].Version' --output text 2>&1) || true
        if [ -n "$LIST_OUTPUT" ]; then
          OLD_VERSIONS=$(aws lambda list-layer-versions --layer-name "$LAYER_NAME" --query 'LayerVersions[5:].Version' --output text 2>/dev/null || echo "")
          if [ -n "$OLD_VERSIONS" ]; then
            echo "Deleting old layer versions: $OLD_VERSIONS"
            for version in $OLD_VERSIONS; do
              aws lambda delete-layer-version --layer-name "$LAYER_NAME" --version-number "$version" || true
            done
          fi
        fi
      # Deploy Lambda Layer
      - |
        echo "Deploying Lambda Layer..."
        PUBLISH_OUTPUT=$(aws lambda publish-layer-version \
          --layer-name "${LAYER_NAME}" \
          --description "Shared utilities and types for Mnemosyne Slack functions" \
          --zip-file fileb://slack-shared-layer.zip \
          --compatible-runtimes nodejs20.x \
          --compatible-architectures arm64 \
          --output json 2>&1)
        PUBLISH_EXIT_CODE=$?
        if [ $PUBLISH_EXIT_CODE -ne 0 ]; then
          echo "ERROR: Failed to publish layer version:"
          echo "$PUBLISH_OUTPUT"
          exit 1
        fi
        LAYER_VERSION=$(echo "$PUBLISH_OUTPUT" | grep -oE '"Version"[[:space:]]*:[[:space:]]*[0-9]+' | grep -oE '[0-9]+' | head -1)
        if [ -z "$LAYER_VERSION" ] || ! [[ "$LAYER_VERSION" =~ ^[0-9]+$ ]]; then
          echo "ERROR: Invalid layer version returned"
          echo "$PUBLISH_OUTPUT"
          exit 1
        fi
        LAYER_ARN=$(aws lambda get-layer-version \
          --layer-name "${LAYER_NAME}" \
          --version-number "${LAYER_VERSION}" \
          --query 'LayerVersionArn' --output text 2>&1)
        if [ $? -ne 0 ] || [ -z "$LAYER_ARN" ]; then
          echo "ERROR: Failed to get layer ARN"
          exit 1
        fi
        echo "✓ Layer version ${LAYER_VERSION} published: ${LAYER_ARN}"
        echo "LAYER_ARN=${LAYER_ARN}" > layer-arn.env
      # Deploy all Lambda functions
      - |
        source layer-arn.env
        # Convert kebab-case to PascalCase for function names
        for func in message-listener file-processor oauth-callback; do
          # Convert message-listener -> MessageListener
          FUNCTION_NAME=$(echo "$func" | sed 's/-\([a-z]\)/\U\1/g' | sed 's/^\([a-z]\)/\U\1/')
          FUNCTION_NAME="${APP_PREFIX}${FUNCTION_NAME}"
          FUNCTION_ZIP="${func}-function.zip"
          if [ ! -f "$FUNCTION_ZIP" ]; then
            echo "WARNING: $FUNCTION_ZIP not found, skipping $func"
            continue
          fi
          echo "Deploying $FUNCTION_NAME..."
          aws lambda update-function-code \
            --function-name "$FUNCTION_NAME" \
            --zip-file "fileb://${FUNCTION_ZIP}"
          aws lambda update-function-configuration \
            --function-name "$FUNCTION_NAME" \
            --layers "$LAYER_ARN"
          echo "✓ $FUNCTION_NAME deployed with layer"
        done
      - echo ""
      - echo "✓ All Lambda functions deployed successfully"
