version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo " Installing Node.js 20 "
      - n 20
      - node --version
      - npm --version
  pre_build:
    commands:
      - echo " Installing all dependencies "
      - cd functions && npm run install:all
      - echo " Building all Lambda functions "
      - npm run build:all && cd ..
      - echo "✓ All functions built successfully"

  build:
    commands:
      - echo " Packaging and deploying Lambda functions "
      - |
        export APP_PREFIX="${APP_PREFIX:-Mnemosyne}"
        
        # Function: message-listener
        echo "Packaging message-listener..."
        cd functions/message-listener/dist
        zip -rq ../../../message-listener-function.zip .
        cd ../../..
        aws lambda update-function-code \
          --function-name "${APP_PREFIX}MessageListener" \
          --zip-file fileb://message-listener-function.zip
        echo "✓ message-listener deployed"
      - |
        export APP_PREFIX="${APP_PREFIX:-Mnemosyne}"
        
        # Function: file-processor
        echo "Packaging file-processor..."
        cd functions/file-processor/dist
        zip -rq ../../../file-processor-function.zip .
        cd ../../..
        aws lambda update-function-code \
          --function-name "${APP_PREFIX}FileProcessor" \
          --zip-file fileb://file-processor-function.zip
        echo "✓ file-processor deployed"
      - |
        export APP_PREFIX="${APP_PREFIX:-Mnemosyne}"
        
        # Function: oauth-callback
        echo "Packaging oauth-callback..."
        cd functions/oauth-callback/dist
        zip -rq ../../../oauth-callback-function.zip .
        cd ../../..
        aws lambda update-function-code \
          --function-name "${APP_PREFIX}OAuthCallback" \
          --zip-file fileb://oauth-callback-function.zip
        echo "✓ oauth-callback deployed"
      - echo " All Lambda functions built and deployed successfully "

cache:
  key: lambdas-$(codebuild-hash-files package-lock.json package.json functions/*/package.json functions/slack-shared/package.json)
  paths:
    - 'node_modules/**/*'
    - 'functions/*/node_modules/**/*'
    - 'functions/slack-shared/node_modules/**/*'

artifacts:
  files:
    - 'message-listener-function.zip'
    - 'file-processor-function.zip'
    - 'oauth-callback-function.zip'
  name: LambdaArtifacts