version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - n 20 
      - node --version
      - npm --version
      
      # PHASE 1 - Build slack-shared as Lambda Layer
      - echo ""
      - echo "PHASE 1 - Building slack-shared Lambda Layer"
      - |
        if [ -d "functions/slack-shared" ]; then
          cd functions/slack-shared
          npm ci || npm install
          npm run build || (echo "Build failed!" && exit 1)
          # Tests temporarily disabled in CI - running locally
          npm test || true
          echo "✓ slack-shared built successfully"
          cd ../..
        else
          echo "ERROR: functions/slack-shared directory not found!"
          exit 1
        fi

  build:
    commands:
          # PHASE 0 - Clean up old infrastructure (if needed)
          - echo ""
          - echo "PHASE 0 - Cleaning up old infrastructure"
          - |
            # Check for old Lambda layer versions (keep only last 5 versions)
            LAYER_NAME="${APP_PREFIX}SlackSharedLayer"
            LIST_OUTPUT=$(aws lambda list-layer-versions --layer-name "$LAYER_NAME" --query 'LayerVersions[].Version' --output text 2>&1)
            LIST_EXIT_CODE=$?
            if [ $LIST_EXIT_CODE -eq 0 ] && [ -n "$LIST_OUTPUT" ]; then
              OLD_VERSIONS=$(aws lambda list-layer-versions --layer-name "$LAYER_NAME" --query 'LayerVersions[5:].Version' --output text 2>/dev/null || echo "")
              if [ -n "$OLD_VERSIONS" ]; then
                echo "Cleaning up old layer versions: $OLD_VERSIONS"
                for version in $OLD_VERSIONS; do
                  echo "Deleting layer version: $version"
                  aws lambda delete-layer-version --layer-name "$LAYER_NAME" --version-number "$version" || true
                done
              else
                echo "No old layer versions to clean up"
              fi
            else
              echo "Layer does not exist yet or access denied (will be created on first publish)"
            fi
      
      # PHASE 2 - Package slack-shared as Lambda Layer
      - echo ""
      - echo "PHASE 2 - Packaging slack-shared as Lambda Layer"
      - |
        # Create Lambda Layer structure: nodejs/node_modules/mnemosyne-slack-shared
        # For Node.js layers, structure must be: nodejs/node_modules/<package-name>/
        mkdir -p build-layer/nodejs/node_modules/mnemosyne-slack-shared
        
        # Copy built dist and package.json to layer
        cp -r functions/slack-shared/dist build-layer/nodejs/node_modules/mnemosyne-slack-shared/
        cp functions/slack-shared/package.json build-layer/nodejs/node_modules/mnemosyne-slack-shared/
        
        # Install production dependencies for slack-shared into layer
        cd functions/slack-shared
        npm ci --production || npm install --production
        # Copy node_modules dependencies to layer (excluding slack-shared itself if present)
        if [ -d "node_modules" ]; then
          cp -r node_modules/* build-layer/nodejs/node_modules/mnemosyne-slack-shared/node_modules/ 2>/dev/null || true
        fi
        cd ../..
        
        # Package the layer
        cd build-layer
        zip -rq ../slack-shared-layer.zip nodejs 2>&1 | head -20 || true
        cd ..
        echo "✓ slack-shared layer packaged"
      
      # PHASE 3 - Deploy Lambda Layer
      - echo ""
      - echo "PHASE 3 - Deploying Lambda Layer"
      - |
        LAYER_NAME="${APP_PREFIX}SlackSharedLayer"
        # Check if layer exists, create if not
        LAYER_ARN=$(aws lambda list-layers --query "Layers[?LayerName=='${LAYER_NAME}'].LatestMatchingVersion.LayerVersionArn" --output text 2>/dev/null || echo "")
        
        if [ -z "$LAYER_ARN" ]; then
          echo "Layer does not exist, creating..."
          # Create new layer - we'll publish a version in the next step
          echo "Layer will be created on first publish"
        fi
        
        # Publish new layer version
        # Publish and capture JSON output, then extract version number
        PUBLISH_OUTPUT=$(aws lambda publish-layer-version \
          --layer-name "${LAYER_NAME}" \
          --description "Shared utilities and types for Mnemosyne Slack functions" \
          --zip-file fileb://slack-shared-layer.zip \
          --compatible-runtimes nodejs20.x \
          --compatible-architectures arm64 \
          --output json 2>&1)
        
        PUBLISH_EXIT_CODE=$?
        
        if [ $PUBLISH_EXIT_CODE -ne 0 ]; then
          echo "ERROR: Failed to publish layer version:"
          echo "$PUBLISH_OUTPUT"
          exit 1
        fi
        
        # Extract version number from JSON (handles both JSON and error messages)
        LAYER_VERSION=$(echo "$PUBLISH_OUTPUT" | grep -oE '"Version"[[:space:]]*:[[:space:]]*[0-9]+' | grep -oE '[0-9]+' | head -1)
        
        # Verify layer version is a valid number
        if [ -z "$LAYER_VERSION" ] || ! [[ "$LAYER_VERSION" =~ ^[0-9]+$ ]]; then
          echo "ERROR: Invalid layer version returned from publish"
          echo "Publish output: $PUBLISH_OUTPUT"
          exit 1
        fi
        
        # Get layer ARN for the published version
        LAYER_ARN=$(aws lambda get-layer-version \
          --layer-name "${LAYER_NAME}" \
          --version-number "${LAYER_VERSION}" \
          --query 'LayerVersionArn' --output text 2>&1)
        
        if [ $? -ne 0 ] || [ -z "$LAYER_ARN" ]; then
          echo "ERROR: Failed to get layer ARN for version ${LAYER_VERSION}"
          exit 1
        fi
        
        echo "✓ Layer version ${LAYER_VERSION} published: ${LAYER_ARN}"
      
      # PHASE 4 - Build and deploy each Lambda function
      - echo ""
      - echo "PHASE 4 - Building Lambda Functions"
      
      # Build message-listener
      - echo "Building message-listener..."
      - |
        if [ -d "functions/message-listener" ]; then
          cd functions/message-listener
          # Remove slack-shared from node_modules (will come from layer)
          rm -rf node_modules/mnemosyne-slack-shared || true
          npm ci || npm install
          npm run build || (echo "Build failed!" && exit 1)
          # Tests temporarily disabled in CI - running locally
          # npm test || true
          echo "✓ message-listener built successfully"
          cd ../..
        else
          echo "ERROR: functions/message-listener directory not found!"
          exit 1
        fi
      
      # Build file-processor
      - echo "Building file-processor..."
      - |
        if [ -d "functions/file-processor" ]; then
          cd functions/file-processor
          # Remove slack-shared from node_modules (will come from layer)
          rm -rf node_modules/mnemosyne-slack-shared || true
          npm ci || npm install
          npm run build || (echo "Build failed!" && exit 1)
          # Tests temporarily disabled in CI - running locally
          # npm test || true
          echo "✓ file-processor built successfully"
          cd ../..
        else
          echo "ERROR: functions/file-processor directory not found!"
          exit 1
        fi
      
      # Build oauth-callback
      - echo "Building oauth-callback..."
      - |
        if [ -d "functions/oauth-callback" ]; then
          cd functions/oauth-callback
          # Remove slack-shared from node_modules (will come from layer)
          rm -rf node_modules/mnemosyne-slack-shared || true
          npm ci || npm install
          npm run build || (echo "Build failed!" && exit 1)
          # Tests temporarily disabled in CI - running locally
          # npm test || true
          echo "✓ oauth-callback built successfully"
          cd ../..
        else
          echo "ERROR: functions/oauth-callback directory not found!"
          exit 1
        fi
      
      - echo "All Node.js apps built successfully"
      - echo ""
      
      # PHASE 5 - Package Lambda functions
      - echo "PHASE 5 - Creating deployment packages"
      
      # Package message-listener
      - echo "Creating package for message-listener..."
      - |
        cd functions/message-listener
        npm prune --production || true
        if [ -d "dist" ]; then
          cd dist
          zip -rq ../../../message-listener-function.zip * 2>&1 | head -20 || true
          cd ..
        fi
        if [ -d "node_modules" ]; then
          zip -rq ../../message-listener-function.zip node_modules 2>&1 | head -20 || true
        fi
        cd ../..
        echo "✓ message-listener package created"
      
      # Package file-processor
      - echo "Creating package for file-processor..."
      - |
        cd functions/file-processor
        npm prune --production || true
        if [ -d "dist" ]; then
          cd dist
          zip -rq ../../../file-processor-function.zip * 2>&1 | head -20 || true
          cd ..
        fi
        if [ -d "node_modules" ]; then
          zip -rq ../../file-processor-function.zip node_modules 2>&1 | head -20 || true
        fi
        cd ../..
        echo "✓ file-processor package created"
      
      # Package oauth-callback
      - echo "Creating package for oauth-callback..."
      - |
        cd functions/oauth-callback
        npm prune --production || true
        if [ -d "dist" ]; then
          cd dist
          zip -rq ../../../oauth-callback-function.zip * 2>&1 | head -20 || true
          cd ..
        fi
        if [ -d "node_modules" ]; then
          zip -rq ../../oauth-callback-function.zip node_modules 2>&1 | head -20 || true
        fi
        cd ../..
        echo "✓ oauth-callback package created"
      
      - echo "All deployment packages created"
      - echo ""
      
      # PHASE 6 - Deploy Lambda functions with layer
      - echo "PHASE 6 - Deploying Lambda functions with layer"
      
      # Deploy message-listener
      - echo "Deploying message-listener..."
      - |
        FUNCTION_NAME="${APP_PREFIX}MessageListener"
        # Get latest layer version ARN
        LAYER_NAME="${APP_PREFIX}SlackSharedLayer"
        LAYER_ARN_OUTPUT=$(aws lambda list-layer-versions \
          --layer-name "${LAYER_NAME}" \
          --max-items 1 \
          --query 'LayerVersions[0].LayerVersionArn' \
          --output text 2>&1)
        LAYER_EXIT_CODE=$?
        
        # Validate layer ARN - must start with "arn:aws:" and not be empty
        if [ $LAYER_EXIT_CODE -ne 0 ] || [ -z "$LAYER_ARN_OUTPUT" ] || [[ ! "$LAYER_ARN_OUTPUT" =~ ^arn:aws: ]]; then
          echo "ERROR: Failed to get latest layer ARN for ${LAYER_NAME}"
          echo "Exit code: $LAYER_EXIT_CODE"
          echo "Output: $LAYER_ARN_OUTPUT"
          exit 1
        fi
        LAYER_ARN="$LAYER_ARN_OUTPUT"
        
        # Update function code
        aws lambda update-function-code \
          --function-name "$FUNCTION_NAME" \
          --zip-file fileb://message-listener-function.zip
        
        # Update function configuration to include layer
        aws lambda update-function-configuration \
          --function-name "$FUNCTION_NAME" \
          --layers "$LAYER_ARN"
        
        echo "✓ message-listener deployed with layer ${LAYER_ARN}"
      
      # Deploy file-processor
      - echo "Deploying file-processor..."
      - |
        FUNCTION_NAME="${APP_PREFIX}FileProcessor"
        LAYER_NAME="${APP_PREFIX}SlackSharedLayer"
        LAYER_ARN_OUTPUT=$(aws lambda list-layer-versions \
          --layer-name "${LAYER_NAME}" \
          --max-items 1 \
          --query 'LayerVersions[0].LayerVersionArn' \
          --output text 2>&1)
        LAYER_EXIT_CODE=$?
        
        # Validate layer ARN - must start with "arn:aws:" and not be empty
        if [ $LAYER_EXIT_CODE -ne 0 ] || [ -z "$LAYER_ARN_OUTPUT" ] || [[ ! "$LAYER_ARN_OUTPUT" =~ ^arn:aws: ]]; then
          echo "ERROR: Failed to get latest layer ARN for ${LAYER_NAME}"
          echo "Exit code: $LAYER_EXIT_CODE"
          echo "Output: $LAYER_ARN_OUTPUT"
          exit 1
        fi
        LAYER_ARN="$LAYER_ARN_OUTPUT"
        
        aws lambda update-function-code \
          --function-name "$FUNCTION_NAME" \
          --zip-file fileb://file-processor-function.zip
        
        aws lambda update-function-configuration \
          --function-name "$FUNCTION_NAME" \
          --layers "$LAYER_ARN"
        
        echo "✓ file-processor deployed with layer ${LAYER_ARN}"
      
      # Deploy oauth-callback
      - echo "Deploying oauth-callback..."
      - |
        FUNCTION_NAME="${APP_PREFIX}OAuthCallback"
        LAYER_NAME="${APP_PREFIX}SlackSharedLayer"
        LAYER_ARN_OUTPUT=$(aws lambda list-layer-versions \
          --layer-name "${LAYER_NAME}" \
          --max-items 1 \
          --query 'LayerVersions[0].LayerVersionArn' \
          --output text 2>&1)
        LAYER_EXIT_CODE=$?
        
        # Validate layer ARN - must start with "arn:aws:" and not be empty
        if [ $LAYER_EXIT_CODE -ne 0 ] || [ -z "$LAYER_ARN_OUTPUT" ] || [[ ! "$LAYER_ARN_OUTPUT" =~ ^arn:aws: ]]; then
          echo "ERROR: Failed to get latest layer ARN for ${LAYER_NAME}"
          echo "Exit code: $LAYER_EXIT_CODE"
          echo "Output: $LAYER_ARN_OUTPUT"
          exit 1
        fi
        LAYER_ARN="$LAYER_ARN_OUTPUT"
        
        aws lambda update-function-code \
          --function-name "$FUNCTION_NAME" \
          --zip-file fileb://oauth-callback-function.zip
        
        aws lambda update-function-configuration \
          --function-name "$FUNCTION_NAME" \
          --layers "$LAYER_ARN"
        
        echo "✓ oauth-callback deployed with layer ${LAYER_ARN}"
      
      - echo ""
      - echo "All Lambda functions deployed successfully with shared layer"
