version: 0.2

phases:
  install:
    # Install Node.js 20 via yum (Amazon Linux 2023 package manager)
    # First check if Node.js is already installed, if not install Node.js 20
    # This avoids GLIBC compatibility issues with nvm-installed binaries
    # Lambda runtime still uses Node.js 22 (NODEJS_22_X) - build environment and runtime are separate
    commands:
      - echo "Checking for Node.js installation..."
      - node --version || echo "Node.js not found, installing..."
      - |
        if ! command -v node &> /dev/null; then
          echo "Installing Node.js 20 via yum (Amazon Linux 2023 package manager)"
          # Try enabling NodeSource repository for Node.js 20
          curl -fsSL https://rpm.nodesource.com/setup_20.x | sudo bash - || true
          # Install Node.js 20 via yum
          sudo yum install -y nodejs || sudo yum install -y nodejs20 || (echo "Node.js installation failed, trying alternative method" && exit 1)
        fi
      - node --version
      - npm --version || echo "npm not found, installing..."
      - |
        if ! command -v npm &> /dev/null; then
          sudo yum install -y npm || echo "npm installation failed"
        fi
      - npm --version
      - echo Building slack-shared dependency
      - |
        if [ -d "functions/slack-shared" ]; then
          cd functions/slack-shared
          npm ci
          npm run build
          echo "✓ slack-shared built successfully"
          cd ../..
        else
          echo "ERROR: functions/slack-shared directory not found!"
          exit 1
        fi
  build:
    commands:
      - echo "Building all Lambda functions"
      - echo "Building message-listener..."
      - |
        if [ -d "functions/message-listener" ]; then
          cd functions/message-listener
          npm ci
          npm run build
          npm test || true
          echo "✓ message-listener built successfully"
          cd ../..
        else
          echo "ERROR: functions/message-listener directory not found!"
          exit 1
        fi
      
      - echo "Building file-processor..."
      - |
        if [ -d "functions/file-processor" ]; then
          cd functions/file-processor
          npm ci
          npm run build
          npm test || true
          echo "✓ file-processor built successfully"
          cd ../..
        else
          echo "ERROR: functions/file-processor directory not found!"
          exit 1
        fi
      
      - echo "Building oauth-callback..."
      - |
        if [ -d "functions/oauth-callback" ]; then
          cd functions/oauth-callback
          npm ci
          npm run build
          npm test || true
          echo "✓ oauth-callback built successfully"
          cd ../..
        else
          echo "ERROR: functions/oauth-callback directory not found!"
          exit 1
        fi
      
      - echo "All Node.js apps built successfully"
      - echo ""
      - echo "PHASE 2 - Creating deployment packages"
      - echo "Creating package for message-listener..."
      - |
        cd functions/message-listener
        npm prune --production
        cd dist
        zip -r ../../../message-listener-function.zip *
        cd ..
        zip -r ../../message-listener-function.zip node_modules
        cd ../..
        echo "✓ message-listener package created"
      - echo "Creating package for file-processor..."
      - |
        cd functions/file-processor
        npm prune --production
        cd dist
        zip -r ../../../file-processor-function.zip *
        cd ..
        zip -r ../../file-processor-function.zip node_modules
        cd ../..
        echo "✓ file-processor package created"
      - echo "Creating package for oauth-callback..."
      - |
        cd functions/oauth-callback
        npm prune --production
        cd dist
        zip -r ../../../oauth-callback-function.zip *
        cd ..
        zip -r ../../oauth-callback-function.zip node_modules
        cd ../..
        echo "✓ oauth-callback package created"
      
      - echo "All deployment packages created"
      - echo ""
      - echo "PHASE 3 - Deploying Lambda functions"
      - echo "Deploying message-listener..."
      - |
        FUNCTION_NAME="${APP_PREFIX}MessageListener"
        aws lambda update-function-code --function-name "$FUNCTION_NAME" --zip-file fileb://message-listener-function.zip
        echo "✓ message-listener deployed"
      - echo "Deploying file-processor..."
      - |
        FUNCTION_NAME="${APP_PREFIX}FileProcessor"
        aws lambda update-function-code --function-name "$FUNCTION_NAME" --zip-file fileb://file-processor-function.zip
        echo "✓ file-processor deployed"
      - echo "Deploying oauth-callback..."
      - |
        FUNCTION_NAME="${APP_PREFIX}OAuthCallback"
        aws lambda update-function-code --function-name "$FUNCTION_NAME" --zip-file fileb://oauth-callback-function.zip
        echo "✓ oauth-callback deployed"
      
      - echo ""
      - echo "All Lambda functions deployed successfully"
