version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - n 20
      - node --version
      - npm --version
      - npm install

  pre_build:
    commands:
      - node infrastructure/scripts/setup-lambdas-env.js
      - export LAYER_ARN="${LAYER_ARN}"

  build:
    commands:
      - npm run build:lambdas
      - npm run deploy:lambdas

artifacts:
  files:
    - 'message-listener-function.zip'
    - 'file-processor-function.zip'
    - 'oauth-callback-function.zip'
  name: LambdaArtifacts