version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - n 20
      - node --version
      - npm --version
      - npm install

  pre_build:
    commands:
      - echo "=== Checking for layer changes ==="
      - BUILD_TYPE=layer node infrastructure/scripts/check-changes.js
      - source build-changes.env
      - echo "HAS_CHANGES=${HAS_CHANGES}"
      - |
        if [ "${HAS_CHANGES}" = "false" ]; then
          echo "No changes detected - skipping layer build"
          exit 0
        else
          echo "Changes detected - proceeding with build"
          cd functions/slack-shared && npm ci || npm install && cd ../..
        fi

  build:
    commands:
      - source build-changes.env || true
      - |
        if [ "${HAS_CHANGES:-true}" = "false" ]; then
          echo "Skipping build phase - no changes"
          exit 0
        fi
      - npm run build:layer

cache:
  key: layer-$(codebuild-hash-files package-lock.json package.json functions/slack-shared/package.json merged-deps/package.json)
  paths:
    - 'node_modules/**/*'
    - 'functions/slack-shared/node_modules/**/*'
    - 'merged-deps/node_modules/**/*'

artifacts:
  files:
    - 'shared-node-modules.zip'
    - 'shared-node-modules.tar.gz'
    - 'layer-arn.env'
    - 'merged-deps/package.json'
  name: LayerArtifact
