version: 0.2

phases:
  install:
    commands:
      - aws --version
      - echo "=== Deploying Lambda Layer ==="

  build:
    commands:
      - |
        APP_PREFIX="${APP_PREFIX:-Mnemosyne}"
        LAYER_NAME="${APP_PREFIX}SlackSharedLayer"
        echo "Layer Name: ${LAYER_NAME}"
      # Cleanup old layer versions (keep last 5)
      - |
        echo "Cleaning up old layer versions..."
        LIST_OUTPUT=$(aws lambda list-layer-versions --layer-name "$LAYER_NAME" --query 'LayerVersions[].Version' --output text 2>&1) || true
        if [ -n "$LIST_OUTPUT" ]; then
          OLD_VERSIONS=$(aws lambda list-layer-versions --layer-name "$LAYER_NAME" --query 'LayerVersions[5:].Version' --output text 2>/dev/null || echo "")
          if [ -n "$OLD_VERSIONS" ]; then
            echo "Deleting old layer versions: $OLD_VERSIONS"
            for version in $OLD_VERSIONS; do
              aws lambda delete-layer-version --layer-name "$LAYER_NAME" --version-number "$version" || true
            done
          fi
        fi
      # Deploy Lambda Layer
      - |
        echo "Deploying Lambda Layer..."
        PUBLISH_OUTPUT=$(aws lambda publish-layer-version \
          --layer-name "${LAYER_NAME}" \
          --description "Shared utilities and types for Mnemosyne Slack functions" \
          --zip-file fileb://slack-shared-layer.zip \
          --compatible-runtimes nodejs20.x \
          --compatible-architectures arm64 \
          --output json 2>&1)
        PUBLISH_EXIT_CODE=$?
        if [ $PUBLISH_EXIT_CODE -ne 0 ]; then
          echo "ERROR: Failed to publish layer version:"
          echo "$PUBLISH_OUTPUT"
          exit 1
        fi
        LAYER_VERSION=$(echo "$PUBLISH_OUTPUT" | grep -oE '"Version"[[:space:]]*:[[:space:]]*[0-9]+' | grep -oE '[0-9]+' | head -1)
        if [ -z "$LAYER_VERSION" ] || ! [[ "$LAYER_VERSION" =~ ^[0-9]+$ ]]; then
          echo "ERROR: Invalid layer version returned"
          echo "$PUBLISH_OUTPUT"
          exit 1
        fi
        LAYER_ARN=$(aws lambda get-layer-version \
          --layer-name "${LAYER_NAME}" \
          --version-number "${LAYER_VERSION}" \
          --query 'LayerVersionArn' --output text 2>&1)
        if [ $? -ne 0 ] || [ -z "$LAYER_ARN" ]; then
          echo "ERROR: Failed to get layer ARN"
          exit 1
        fi
        echo "✓ Layer version ${LAYER_VERSION} published: ${LAYER_ARN}"
        echo "LAYER_ARN=${LAYER_ARN}" > layer-arn.env
        # Export layer ARN to S3 for other stages to use
        aws s3 cp layer-arn.env s3://${ARTIFACT_BUCKET}/layer-arn.env || true

artifacts:
  files:
    - 'layer-arn.env'
  name: LayerArnArtifact
