version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies for slack-shared..."
      - |
        if [ -d "functions/slack-shared" ]; then
          cd functions/slack-shared
          npm ci
          npm run build
          cd ../..
        else
          echo "WARNING: functions/slack-shared directory not found, skipping..."
        fi
      - echo "Installing dependencies for message-listener..."
      - |
        if [ -d "functions/message-listener" ]; then
          cd functions/message-listener
          npm ci
          cd ../..
        else
          echo "ERROR: functions/message-listener directory not found!"
          exit 1
        fi
  build:
    commands:
      - echo "Building message-listener Lambda function..."
      - |
        if [ -d "functions/message-listener" ]; then
          cd functions/message-listener
          npm run build
          npm test || true
          cd ../..
        else
          echo "ERROR: functions/message-listener directory not found!"
          exit 1
        fi
      - echo "Creating deployment package..."
      - cd functions/message-listener
      - echo "Pruning dev dependencies..."
      - npm prune --production
      - echo "Creating zip with proper structure..."
      - cd dist
      - zip -r ../../../message-listener-function.zip *
      - cd ..
      - zip -r ../../message-listener-function.zip node_modules
      - cd ../..
      - echo "Deploying Lambda function via pipeline..."
      - |
        if [ -z "$FUNCTION_NAME" ]; then
          FUNCTION_NAME="MnemosyneMessageListener"
        fi
        aws lambda update-function-code --function-name "$FUNCTION_NAME" --zip-file fileb://message-listener-function.zip
      - echo "Lambda deployment complete"