version: 0.2

runtime-versions:
  nodejs: 22

phases:
  install:
    commands:
      - echo "Installing dependencies for slack-shared..."
      - |
        if [ -d "slack-shared" ]; then
          cd slack-shared
          npm ci
          cd ..
        else
          echo "WARNING: slack-shared directory not found, skipping..."
        fi
      - echo "Installing dependencies for message-listener..."
      - |
        if [ -d "message-listener" ]; then
          cd message-listener
          npm ci
          cd ..
        else
          echo "ERROR: message-listener directory not found!"
          exit 1
        fi
  build:
    commands:
      - echo "Building slack-shared dependency..."
      - |
        if [ -d "slack-shared" ]; then
          cd slack-shared
          npm run build
          cd ..
        else
          echo "WARNING: slack-shared directory not found, skipping build..."
        fi
      - echo "Building message-listener Lambda function..."
      - |
        if [ -d "message-listener" ]; then
          cd message-listener
          npm run build
          npm test || true
          cd ..
        else
          echo "ERROR: message-listener directory not found!"
          exit 1
        fi
      - echo "Creating deployment package..."
      - cd message-listener
      - echo "Installing production dependencies in dist..."
      - |
        if [ -d "dist" ]; then
          cd dist
          npm ci --production --ignore-scripts || true
          cd ..
        fi
      - zip -r ../message-listener-function.zip dist/* node_modules package.json 2>/dev/null || zip -r ../message-listener-function.zip dist/* node_modules package.json
      - cd ..
      - echo "Deploying Lambda function via pipeline..."
      - |
        if [ -z "$FUNCTION_NAME" ]; then
          FUNCTION_NAME="MnemosyneMessageListener"
        fi
        aws lambda update-function-code --function-name "$FUNCTION_NAME" --zip-file fileb://message-listener-function.zip
      - echo "Lambda deployment complete"