version: 0.2

runtime-versions:
  nodejs: 22

phases:
  install:
    commands:
      - echo "Installing dependencies for slack-shared..."
      - cd slack-shared
      - npm ci
      - echo "Installing dependencies for message-listener..."
      - cd ../message-listener
      - npm ci
  build:
    commands:
      - echo "Building slack-shared dependency..."
      - cd slack-shared
      - npm run build
      - echo "Building message-listener Lambda function..."
      - cd ../message-listener
      - npm run build
      - npm test || true
      - echo "Installing production dependencies..."
      - cd dist
      - npm ci --production --ignore-scripts || true
      - echo "Creating deployment package..."
      - cd ../..
      - zip -r message-listener-function.zip message-listener/dist message-listener/node_modules message-listener/package.json 2>/dev/null || (cd message-listener && zip -r ../message-listener-function.zip dist/* node_modules package.json)
      - echo "Deploying Lambda function via pipeline..."
      - |
        if [ -z "$FUNCTION_NAME" ]; then
          FUNCTION_NAME="MnemosyneMessageListener"
        fi
        aws lambda update-function-code --function-name "$FUNCTION_NAME" --zip-file fileb://message-listener-function.zip
      - echo "Lambda deployment complete - function deployed via pipeline only"