version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies for slack-shared..."
      - |
        if [ -d "slack-shared" ]; then
          cd slack-shared
          npm ci
          cd ..
        else
          echo "WARNING: slack-shared directory not found, skipping..."
        fi
      - echo "Installing dependencies for message-listener..."
      - |
        if [ -d "message-listener" ]; then
          cd message-listener
          npm ci
          cd ..
        else
          echo "ERROR: message-listener directory not found!"
          exit 1
        fi
  build:
    commands:
      - echo "Building slack-shared dependency..."
      - |
        if [ -d "slack-shared" ]; then
          cd slack-shared
          npm run build
          cd ..
        else
          echo "WARNING: slack-shared directory not found, skipping build..."
        fi
      - echo "Building message-listener Lambda function..."
      - |
        if [ -d "message-listener" ]; then
          cd message-listener
          npm run build
          npm test || true
          cd ..
        else
          echo "ERROR: message-listener directory not found!"
          exit 1
        fi
      - echo "Creating deployment package..."
      - cd message-listener
      - echo "Pruning dev dependencies..."
      - npm prune --production
      - echo "Creating zip with proper structure..."
      - cd dist
      - zip -r ../../message-listener-function.zip *
      - cd ..
      - zip -r ../message-listener-function.zip node_modules
      - cd ..
      - echo "Deploying Lambda function via pipeline..."
      - |
        if [ -z "$FUNCTION_NAME" ]; then
          FUNCTION_NAME="MnemosyneMessageListener"
        fi
        aws lambda update-function-code --function-name "$FUNCTION_NAME" --zip-file fileb://message-listener-function.zip
      - echo "Lambda deployment complete"