version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies for slack-shared..."
      - |
        if [ -d "functions/slack-shared" ]; then
          cd functions/slack-shared
          npm ci
          cd ../..
        else
          echo "WARNING: functions/slack-shared directory not found, skipping..."
        fi
      - echo "Installing dependencies for oauth-callback..."
      - |
        if [ -d "functions/oauth-callback" ]; then
          cd functions/oauth-callback
          npm ci
          cd ../..
        else
          echo "ERROR: functions/oauth-callback directory not found!"
          exit 1
        fi
  build:
    commands:
      - echo "Building slack-shared dependency..."
      - |
        if [ -d "functions/slack-shared" ]; then
          cd functions/slack-shared
          npm run build
          cd ../..
        else
          echo "WARNING: functions/slack-shared directory not found, skipping build..."
        fi
      - echo "Building oauth-callback Lambda function..."
      - |
        if [ -d "functions/oauth-callback" ]; then
          cd functions/oauth-callback
          npm run build
          npm test || true
          cd ../..
        else
          echo "ERROR: functions/oauth-callback directory not found!"
          exit 1
        fi
      - echo "Creating deployment package..."
      - cd functions/oauth-callback
      - echo "Pruning dev dependencies..."
      - npm prune --production
      - echo "Creating zip with proper structure..."
      - cd dist
      - zip -r ../../../oauth-callback-function.zip *
      - cd ..
      - zip -r ../../oauth-callback-function.zip node_modules
      - cd ../..
      - echo "Deploying Lambda function via pipeline..."
      - |
        if [ -z "$FUNCTION_NAME" ]; then
          FUNCTION_NAME="MnemosyneOAuthCallback"
        fi
        aws lambda update-function-code --function-name "$FUNCTION_NAME" --zip-file fileb://oauth-callback-function.zip
      - echo "Lambda deployment complete"

